# Generated by Django 4.2.29 on 2026-04-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0002_sentdocusignenvelope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentflowstep',
            unique_together={('flow', 'step_order')},
        ),
        migrations.AddField(
            model_name='sentdocusignenvelope',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_envelopes', to='documentflow.documentflow'),
        ),
        migrations.AddField(
            model_name='sentdocusignenvelope',
            name='flow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_envelopes', to='documentflow.documentflowstep'),
        ),
    ]
