# Generated by Django 4.2.29 on 2026-04-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0003_alter_documentflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentDocuSignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(blank=True, max_length=50)),
                ('recipient_id_guid', models.CharField(blank=True, max_length=255)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('routing_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided')], default='created', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='documentflow.sentdocusignenvelope')),
            ],
            options={
                'ordering': ['routing_order', 'id'],
                'unique_together': {('sent_envelope', 'recipient_id')},
            },
        ),
    ]
