# Generated by Django 4.2.29 on 2026-04-25 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsign', '0023_signeddocumentfile_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0058_customuser_work_permit_extension_date_and_more'),
        ('documentflow', '0004_sentdocusignrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('work_permit_extension', 'Work Permit Extension'), ('maintained_status', 'Maintained Status'), ('pgwp_application', 'PGWP Application'), ('pr_application', 'PR Application'), ('restoration_application', 'Restoration Application'), ('new_work_permit', 'New Work Permit'), ('study_completed', 'Studies Completed'), ('review_note', 'Review Note'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='Application number, file number, or reference ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_immigration_status_events', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immigration_status_events', to='dsign.signeddocumentfile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immigration_status_events', to='user.employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immigration_status_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
