# Generated by Django 4.2.29 on 2026-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentflow", "0005_immigrationstatusevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immigrationstatusevent",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("work_permit_extension", "Work Permit Extension"),
                    ("maintained_status", "Maintained Status"),
                    ("pgwp_application", "PGWP Application"),
                    ("pr_application", "PR Application"),
                    ("new_work_permit", "New Work Permit"),
                    ("study_completed", "Studies Completed"),
                    ("review_note", "HR Review Note"),
                    (
                        "work_authorization_letter_applied",
                        "Work Authorization Letter Applied",
                    ),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
