# Generated by Django 4.2.29 on 2026-07-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0058_customuser_work_permit_extension_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTargetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_target_categories",
                        to="user.employer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Target Category",
                "verbose_name_plural": "Sales Target Categories",
                "ordering": ["employer", "name"],
                "unique_together": {("employer", "name")},
            },
        ),
        migrations.CreateModel(
            name="SalesTargetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_target_periods",
                        to="user.employer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Target Period",
                "verbose_name_plural": "Sales Target Periods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesTargetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projected_sales",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_lines",
                        to="sales_targets.salestargetcategory",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_lines",
                        to="sales_targets.salestargetperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Target Line",
                "verbose_name_plural": "Sales Target Lines",
                "ordering": ["category__name"],
                "unique_together": {("period", "category")},
            },
        ),
    ]
