# Generated by Django 4.2.29 on 2026-07-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0058_customuser_work_permit_extension_date_and_more"),
        ("sales_targets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salestargetline",
            options={"ordering": ["store_id", "category__name"]},
        ),
        migrations.RenameField(
            model_name="salestargetline",
            old_name="projected_sales",
            new_name="target_amount",
        ),
        migrations.AlterUniqueTogether(
            name="salestargetline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="salestargetline",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_target_lines",
                to="user.store",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salestargetline",
            unique_together={("period", "store", "category")},
        ),
    ]
