# Generated by Django 4.2.29 on 2026-07-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_targets", "0002_alter_salestargetline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestargetline",
            name="current_sales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="salestargetline",
            name="last_updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
