# Generated by Django 4.2.29 on 2026-07-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_targets", "0003_salestargetline_current_sales_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salestargetline",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="salestargetline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
