# Generated by Django 4.2.29 on 2026-07-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0058_customuser_work_permit_extension_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales_targets", "0004_remove_salestargetline_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("imported", "Imported"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="preview",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesImportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("store_number", models.CharField(blank=True, max_length=50)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["store_number", "original_filename"],
            },
        ),
        migrations.CreateModel(
            name="SalesImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_code", models.CharField(max_length=20)),
                ("category_name", models.CharField(max_length=100)),
                (
                    "imported_sales",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "current_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_valid", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["category_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="salestargetcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="salestargetcategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="salestargetcategory",
            name="d365_category_code",
            field=models.CharField(
                blank=True,
                help_text="Category code from the D365 Category Sales Report. Example: 2310",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="salestargetcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("d365_category_code__isnull", False),
                    models.Q(("d365_category_code", ""), _negated=True),
                ),
                fields=("employer", "d365_category_code"),
                name="unique_d365_code_per_employer",
            ),
        ),
        migrations.AddField(
            model_name="salesimportrow",
            name="staged_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="sales_targets.salesimportfile",
            ),
        ),
        migrations.AddField(
            model_name="salesimportrow",
            name="target_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staged_import_rows",
                to="sales_targets.salestargetcategory",
            ),
        ),
        migrations.AddField(
            model_name="salesimportfile",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="sales_targets.salesimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_import_batches",
                to="user.employer",
            ),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="salesimportrow",
            constraint=models.UniqueConstraint(
                fields=("staged_file", "target_category"),
                name="unique_category_per_staged_sales_file",
            ),
        ),
    ]
