# Generated by Django 4.2.29 on 2026-07-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sales_targets",
            "0005_salesimportbatch_salesimportfile_salesimportrow_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="salesimportbatch",
            name="target_period",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="sales_targets.salestargetperiod",
            ),
            preserve_default=False,
        ),
    ]
