# Generated by Django 4.2.29 on 2026-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_targets", "0006_salesimportbatch_target_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestargetcategory",
            name="measurement_type",
            field=models.CharField(
                choices=[("sales", "Dollar Sales"), ("units", "Units Sold")],
                default="sales",
                max_length=20,
            ),
        ),
    ]
