# Generated by Django 4.2.29 on 2026-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_targets", "0007_salestargetcategory_measurement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestargetline",
            name="current_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
