# Generated by Django 4.2.3 on 2023-07-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mon_avail",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
