# Generated by Django 4.2.3 on 2023-07-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_mon_avail"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fri_avail",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sat_avail",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sun_avail",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="thu_avail",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tue_avail",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wed_avail",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
