# Generated by Django 4.2.3 on 2023-07-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_fri_avail_customuser_sat_avail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sin",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
