# Generated by Django 4.2.3 on 2023-07-16 19:17

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_employer_customuser_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="address_two",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="state_province",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
