# Generated by Django 4.2.3 on 2023-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_employer_address_employer_address_two_employer_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Twimlmessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("twimlname", models.CharField(max_length=100)),
                ("twimlid", models.CharField(max_length=100)),
            ],
        ),
    ]
