# Generated by Django 4.2.3 on 2023-07-16 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_twimlmessages"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Twimlmessages",
        ),
    ]
