# Generated by Django 4.2.3 on 2023-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="address_two",
            field=models.CharField(max_length=100),
        ),
    ]
