# Generated by Django 4.2.3 on 2023-07-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_store_address_two"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="address_two",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
