# Generated by Django 4.2.3 on 2023-07-16 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_store_address_two"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="state_province",
            new_name="province",
        ),
    ]
