# Generated by Django 4.2.3 on 2023-08-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_rename_state_province_store_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="employer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store",
                to="user.employer",
            ),
        ),
    ]
