# Generated by Django 4.2.3 on 2023-11-12 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0017_customuser_address_customuser_address_two_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="postal",
            field=models.CharField(
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid postal code format (e.g., 123-4567).",
                        regex="^\\d{3}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
