# Generated by Django 4.2.3 on 2023-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_customuser_postal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="postal",
            field=models.CharField(max_length=7, null=True),
        ),
    ]
