# Generated by Django 4.2.3 on 2023-11-29 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_customuser_address_two"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="fri_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mon_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sat_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sun_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="thu_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tue_avail",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="wed_avail",
        ),
    ]
