# Generated by Django 4.2.3 on 2023-11-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_remove_customuser_fri_avail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("error_message", models.TextField()),
            ],
        ),
    ]
