# Generated by Django 4.2.10 on 2024-06-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0024_customuser_store_alter_usermanager_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_stores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
