# Generated by Django 4.2.10 on 2024-12-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0027_remove_externalrecipient_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrecipient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
