# Generated by Django 4.2.10 on 2025-01-27 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0029_documenttype_employeedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedocument",
            name="file",
        ),
    ]
