# Generated by Django 4.2.10 on 2025-02-02 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0030_remove_employeedocument_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_opt_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
