# Generated by Django 4.2.10 on 2025-02-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0031_smsoptout"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerSMSTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_tasks",
                        to="user.employer",
                    ),
                ),
            ],
            options={
                "unique_together": {("employer", "task_name")},
            },
        ),
    ]
