# Generated by Django 4.2.10 on 2025-02-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0032_employersmstask"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="verified_sender_email",
            field=models.EmailField(
                blank=True,
                help_text="The verified sender email in SendGrid for this employer.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
