# Generated by Django 4.2.10 on 2025-02-20 21:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_employer_verified_sender_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Enter a phone number (e.g., 519-555-1234 or +15195551234)",
                        max_length=128,
                        region=None,
                    ),
                ),
            ],
        ),
    ]
