# Generated by Django 4.2.10 on 2025-02-20 23:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0034_phoneentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Enter a phone number (e.g., 519-555-1234 or +15195551234)",
                max_length=128,
                region=None,
            ),
        ),
    ]
