# Generated by Django 4.2.10 on 2025-02-21 13:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0035_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sin_expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="SIN Expiration Date"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="work_permit_expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Work Permit Expiration Date"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Enter a phone number", max_length=128, region=None
            ),
        ),
    ]
