# Generated by Django 4.2.10 on 2025-03-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0036_customuser_sin_expiration_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_new_hire_file", models.BooleanField(default=True)),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="user.employer",
                    ),
                ),
            ],
        ),
    ]
