# Generated by Django 4.2.10 on 2025-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0037_employersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="senior_contact_name",
            field=models.CharField(
                blank=True,
                help_text="The senior contact person for this employer (e.g., HR Manager, Director).",
                max_length=255,
                null=True,
            ),
        ),
    ]
