# Generated by Django 4.2.10 on 2025-03-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0038_employer_senior_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsoptout",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                help_text="Employer associated with this opt-out.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_opt_outs",
                to="user.employer",
            ),
        ),
    ]
