# Generated by Django 4.2.10 on 2025-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0039_smsoptout_employer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="verified_sender_email",
        ),
        migrations.AddField(
            model_name="employer",
            name="verified_sender_local",
            field=models.CharField(
                blank=True,
                help_text="Enter only the part before '@yourdomain.com'",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
