# Generated by Django 4.2.10 on 2025-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0040_remove_employer_verified_sender_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="verified_sender_email",
            field=models.EmailField(
                blank=True,
                help_text="This is the full email generated based on your input.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
