# Generated by Django 4.2.10 on 2025-03-05 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0041_employer_verified_sender_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewHireInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("CSR", "CSR"), ("HR", "HR"), ("Manager", "Manager")],
                        max_length=100,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=django.utils.crypto.get_random_string,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="user.employer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.store",
                    ),
                ),
            ],
        ),
    ]
