# Generated by Django 4.2.10 on 2025-03-08 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0042_newhireinvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newhireinvite",
            name="store",
        ),
    ]
