# Generated by Django 4.2.10 on 2025-03-08 19:49

import arl.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0043_remove_newhireinvite_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newhireinvite",
            name="token",
            field=models.CharField(
                default=arl.user.models.generate_random_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
