# Generated by Django 4.2.10 on 2025-03-08 23:11

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0045_employerrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerrequest",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employerrequest",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="employerrequest",
            name="submitted_at",
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="address_two",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="senior_contact_name",
            field=models.CharField(
                blank=True,
                help_text="The senior contact person for this employer (e.g., HR Manager, Director).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="state_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="verified_sender_email",
            field=models.EmailField(
                blank=True,
                help_text="This is the full email generated based on your input.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="verified_sender_local",
            field=models.CharField(
                blank=True,
                help_text="Enter only the part before '@yourdomain.com'",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employerrequest",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
