# Generated by Django 4.2.10 on 2025-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0046_remove_employerrequest_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerrequest",
            name="email",
            field=models.EmailField(
                default="",
                help_text="Contact email for the employer",
                max_length=254,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
