# Generated by Django 4.2.10 on 2025-03-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0047_employerrequest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
