# Generated by Django 4.2.10 on 2025-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0048_employer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
