# Generated by Django 4.2.10 on 2025-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0049_employer_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="address_two",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
