# Generated by Django 4.2.10 on 2025-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0050_alter_employer_address_two"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
