# Generated by Django 4.2.10 on 2025-03-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0051_employer_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newhireinvite",
            name="role",
            field=models.CharField(
                choices=[("GSA", "GSA"), ("HR", "HR"), ("Manager", "Manager")],
                max_length=100,
            ),
        ),
    ]
