# Generated by Django 4.2.10 on 2025-04-02 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0053_stripeplan_stripepayment_employerrequest_stripe_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="employer",
        ),
        migrations.DeleteModel(
            name="EmployerRequest",
        ),
        migrations.DeleteModel(
            name="StripePayment",
        ),
        migrations.DeleteModel(
            name="StripePlan",
        ),
    ]
