# Generated by Django 4.2.20 on 2025-08-30 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newhireinvite",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user (manager/HR) who created this invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
