# Generated by Django 4.2.20 on 2025-10-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0055_newhireinvite_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sin_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sin_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sin_last4",
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
    ]
