# Generated by Django 4.2.20 on 2025-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0056_customuser_sin_encrypted_customuser_sin_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
