# Generated by Django 4.2.29 on 2026-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_permit_extension_date',
            field=models.DateField(blank=True, help_text='Date extension was submitted to IRCC', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_permit_extension_requested',
            field=models.BooleanField(default=False),
        ),
    ]
