from django.urls import path

from arl.msg.views import (EmailEventList, FetchTwilioCallsView,
                           SendTemplateWhatsAppView,
                           campaign_setup_view, carwash_targets,
                           click_thank_you, communications,
                           email_event_summary_view,
                           employee_email_report_view, fetch_twilio_data,
                           get_group_emails, get_task_status,
                           message_summary_view, sendgrid_webhook,
                           sendgrid_webhook_view, sms_success_view,
                           template_email_success_view,
                           template_whats_app_success_view, whatsapp_webhook,
                           tobacco_vape_policy_view, sms_summary_view,
                           fetch_sms_data, search_users_view,
                           latest_compliance_file,
                           compliance_file_view,
                           upload_attachment, twilio_short_link_webhook,
                           fetch_shortlink_sms_data, edit_draft_email,
                           delete_draft_email, save_draft_ajax,
                           test_sms_with_short_link)


urlpatterns = [
    path("sendgrid_hook/", sendgrid_webhook, name="sendgrid_webhook"),
    path("sms-success/", sms_success_view, name="sms_success"),
    path(
        "send-whatsapp/",
        SendTemplateWhatsAppView.as_view(),
        name="send_whats_app_template_view",
    ),
    path(
        "template-email-success/",
        template_email_success_view,
        name="template_email_success",
    ),
    path(
        "template-whats_app-success/",
        template_whats_app_success_view,
        name="template_whats_app_success",
    ),
    path(
        "fetch-twilio-calls/", FetchTwilioCallsView.as_view(), name="fetch_twilio_calls"
    ),
    path("api/data/", EmailEventList, name="data-list"),
    path("thank-you/", click_thank_you, name="thank_you"),
    path("comms/", communications, name="comms"),
    path('webhook/whatsapp/', whatsapp_webhook, name='whatsapp_webhook'),
    path('carwash/targets/', carwash_targets, name='carwash_targets'),
    # Route for summarizing costs
    path('message-summary/', message_summary_view, name='summarize_costs'),
    path('fetch-twilio-data/', fetch_twilio_data, name='fetch_twilio_data'),
    path('fetch-sms-data/', fetch_sms_data, name='fetch_sms_data'),
    #path('fetch-shortlink_sms-data/', fetch_shortlink_sms_data, name='fetch_shortened_sms_data'),
    path('sms-summary-view/', sms_summary_view, name='sms_summary_view'),
    path("get-task-status/<str:task_id>/", get_task_status, name="get_task_status"),
    path('sendgrid-webhook/', sendgrid_webhook_view, name='sendgrid_webhook_view'),
    path('email-event-summary/', email_event_summary_view, name='email_event_summary'),
    path("campaign/setup/", campaign_setup_view, name="campaign_setup"),
    path('employee-email-report/', employee_email_report_view, name='employee_email_report'),
    path('get-group-emails/', get_group_emails, name='get_group_emails'),
    path('tobacco-vape-policy/', tobacco_vape_policy_view, name='tobacco_vape_policy'),
    path("search-users/", search_users_view, name="search_users"),
    path("messages/compliance/", latest_compliance_file, name="latest_compliance"),
    path("compliance/", compliance_file_view, name="compliance"),
    path("upload-attachment/", upload_attachment, name="upload_attachment"),
    path("twilio/webhook/short-link/", twilio_short_link_webhook, name="twilio_short_link_webhook"),
    path("short-link-sms/report/", fetch_shortlink_sms_data, name="shortened_sms_report"),
    path("comms/draft/<int:draft_id>/", edit_draft_email, name="edit_draft_email"),
    path("comms/draft/<int:draft_id>/delete/", delete_draft_email, name="delete_draft_email"),
    path("comms/save-draft/", save_draft_ajax, name="save_draft_ajax"),
    path("test-sms/", test_sms_with_short_link, name="test_sms_with_short_link"),
]
