# Generated by Django 4.2.3 on 2023-09-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0002_bulkemailsendgrid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("delivered", "Delivered"),
                            ("open", "Open"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("sg_event_id", models.CharField(max_length=255)),
                ("sg_message_id", models.CharField(max_length=255)),
                ("sg_template_id", models.CharField(max_length=255)),
                ("sg_template_name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("url", models.URLField()),
                ("useragent", models.TextField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
