# Generated by Django 4.2.3 on 2023-09-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msg", "0003_emailevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="username",
            field=models.CharField(default="unknown", max_length=150),
        ),
    ]
