# Generated by Django 4.2.3 on 2023-11-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0004_emailevent_user_emailevent_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
            ],
        ),
    ]
