# Generated by Django 4.2.3 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0005_smslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
        ),
    ]
