# Generated by Django 4.2.3 on 2024-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0008_remove_emailtemplate_content_emailtemplate_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="sg_subject_id",
            field=models.CharField(default="subject", max_length=255),
        ),
        migrations.AlterField(
            model_name="emailevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("delivered", "Delivered"),
                    ("open", "Open"),
                    ("processed", "Processed"),
                    ("deferred", "Deferred"),
                    ("dropped", "Dropped"),
                ],
                max_length=10,
            ),
        ),
    ]
