# Generated by Django 4.2.3 on 2024-01-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0010_remove_emailevent_sg_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailevent",
            name="event",
            field=models.CharField(max_length=10),
        ),
    ]
