# Generated by Django 4.2.10 on 2024-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0011_alter_emailevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name of the WhatsApp template",
                        max_length=255,
                    ),
                ),
                (
                    "content_sid",
                    models.CharField(
                        help_text="The unique identifier for the template (e.g., Twilio Content SID)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this template is used for",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
            },
        ),
    ]
