# Generated by Django 4.2.10 on 2024-04-16 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msg", "0012_whatsapptemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        help_text="Type of consent, e.g., 'SMS', 'Email'",
                        max_length=100,
                    ),
                ),
                (
                    "is_granted",
                    models.BooleanField(
                        default=False, help_text="Whether the user has granted consent"
                    ),
                ),
                (
                    "granted_on",
                    models.DateTimeField(
                        blank=True, help_text="When the consent was granted", null=True
                    ),
                ),
                (
                    "revoked_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the consent was revoked, if applicable",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "consent_type")},
            },
        ),
    ]
