# Generated by Django 4.2.10 on 2024-04-21 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0015_whatsappmessage_action_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=20)),
                ("receiver", models.CharField(max_length=20)),
                ("message_status", models.CharField(max_length=20)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "action_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("template_used", models.BooleanField(default=False)),
                ("message_type", models.CharField(default="WhatsApp", max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="WhatsAppMessage",
        ),
    ]
