# Generated by Django 4.2.10 on 2024-11-22 13:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0017_emaillist"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
