# Generated by Django 4.2.10 on 2024-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0018_emailcontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailcontent",
            name="body",
        ),
        migrations.RemoveField(
            model_name="emailcontent",
            name="subject",
        ),
        migrations.AddField(
            model_name="emailcontent",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
