# Generated by Django 4.2.10 on 2025-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0019_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="template_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
