# Generated by Django 4.2.10 on 2024-12-12 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0019_remove_emailcontent_body_remove_emailcontent_subject_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailContent",
        ),
    ]
