# Generated by Django 4.2.10 on 2025-03-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0036_customuser_sin_expiration_date_and_more"),
        ("msg", "0020_emaillog_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="user.employer",
            ),
        ),
    ]
