# Generated by Django 4.2.10 on 2025-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0036_customuser_sin_expiration_date_and_more"),
        ("msg", "0021_emailtemplate_employer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="employer",
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="employers",
            field=models.ManyToManyField(
                blank=True, related_name="email_templates", to="user.employer"
            ),
        ),
    ]
