# Generated by Django 4.2.10 on 2025-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0022_remove_emailtemplate_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                help_text="The name of the email template (e.g., 'New Hire Onboarding')",
                max_length=100,
                null=True,
            ),
        ),
    ]
