# Generated by Django 4.2.10 on 2025-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0023_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailevent",
            name="useragent",
            field=models.TextField(max_length=1000),
        ),
    ]
