# Generated by Django 4.2.10 on 2025-04-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("msg", "0024_alter_emailevent_useragent"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employer",
            ),
        ),
    ]
