# Generated by Django 4.2.20 on 2025-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0025_emailevent_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Weekly Compliance Policy", max_length=255
                    ),
                ),
                ("file", models.FileField(upload_to="compliance/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
