# Generated by Django 4.2.20 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0026_compliancefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancefile",
            name="presigned_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancefile",
            name="s3_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
