# Generated by Django 4.2.20 on 2025-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0027_compliancefile_presigned_url_compliancefile_s3_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancefile",
            name="presigned_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
