# Generated by Django 4.2.20 on 2025-05-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msg", "0028_alter_compliancefile_presigned_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortenedSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_sid", models.CharField(max_length=64, unique=True)),
                ("to", models.CharField(max_length=20)),
                ("from_number", models.CharField(max_length=20)),
                ("messaging_service_sid", models.CharField(max_length=64)),
                ("account_sid", models.CharField(max_length=64)),
                ("link", models.URLField(blank=True, null=True)),
                ("click_time", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("click", "Clicked"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
