# Generated by Django 4.2.20 on 2025-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0029_shortenedsmslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedsmslog",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
