# Generated by Django 4.2.20 on 2025-05-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0030_alter_shortenedsmslog_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedsmslog",
            name="sms_sid",
            field=models.CharField(max_length=64),
        ),
    ]
