# Generated by Django 4.2.20 on 2025-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0031_alter_shortenedsmslog_sms_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedsmslog",
            name="error_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
