# Generated by Django 4.2.20 on 2025-05-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0032_shortenedsmslog_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedsmslog",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
