# Generated by Django 4.2.20 on 2025-05-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("msg", "0034_draftemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftemail",
            name="employer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.employer",
            ),
            preserve_default=False,
        ),
    ]
