# Generated by Django 4.2.20 on 2025-06-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("msg", "0035_draftemail_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedsmslog",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employer",
            ),
        ),
    ]
