# Generated by Django 4.2.20 on 2025-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("msg", "0036_shortenedsmslog_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("body", models.TextField()),
                ("message_sid", models.CharField(blank=True, max_length=64, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.employer"
                    ),
                ),
            ],
        ),
    ]
