# Generated by Django 4.2.20 on 2025-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0037_smsreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
