# Generated by Django 4.2.20 on 2026-01-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0057_store_is_active"),
        ("msg", "0038_emailevent_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_number", models.CharField(max_length=32)),
                ("from_number", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "campaign_name",
                    models.CharField(default="POS Reboot Reminder", max_length=120),
                ),
                ("twiml_url", models.URLField(blank=True, null=True)),
                (
                    "call_sid",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("queued_ok", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=32, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.employer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
    ]
