# Generated by Django 4.2.28 on 2026-03-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0057_store_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msg", "0039_storecallevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortenedSMSEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("click", "Clicked"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=20, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="ShortenedSMSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sms_sid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("to", models.CharField(db_index=True, max_length=20)),
                ("from_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "messaging_service_sid",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("account_sid", models.CharField(blank=True, max_length=64, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "body_preview",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "short_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secure_link", "Secure Link"),
                            ("new_hire", "New Hire"),
                            ("quiz", "Quiz"),
                            ("document", "Document"),
                            ("notification", "Notification"),
                            ("incident", "Incident"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="secure_link",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "context_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("context_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("clicked", "Clicked"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=20, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("provider_payload", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortened_sms_messages",
                        to="user.employer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortened_sms_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="StoreCallEvent",
        ),
        migrations.AddField(
            model_name="shortenedsmsevent",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="msg.shortenedsmsmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsmessage",
            index=models.Index(
                fields=["employer", "created_at"], name="msg_shorten_employe_65caec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsmessage",
            index=models.Index(
                fields=["user", "created_at"], name="msg_shorten_user_id_2737e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsmessage",
            index=models.Index(
                fields=["status", "created_at"], name="msg_shorten_status_a5afff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsmessage",
            index=models.Index(
                fields=["to", "created_at"], name="msg_shorten_to_a5a5c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsevent",
            index=models.Index(
                fields=["event_type", "event_time"],
                name="msg_shorten_event_t_a1211c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedsmsevent",
            index=models.Index(
                fields=["message", "event_time"], name="msg_shorten_message_519fa5_idx"
            ),
        ),
    ]
