# Generated by Django 4.2.28 on 2026-03-11 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0040_shortenedsmsevent_shortenedsmsmessage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMSReply",
        ),
    ]
