# Generated by Django 4.2.20 on 2025-04-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0003_alter_helpcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpsection",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="helpdesk.helpcategory",
            ),
        ),
    ]
