# Generated by Django 4.2.20 on 2025-04-16 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0004_alter_helpsection_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="helpcategory",
            options={"verbose_name_plural": "Help Categories"},
        ),
    ]
