# Generated by Django 4.2.10 on 2025-01-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0028_externalrecipient_is_active"),
        ("payroll", "0002_payrollinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "overtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="payperiod",
            name="deductions",
        ),
        migrations.RemoveField(
            model_name="payperiod",
            name="gross_pay",
        ),
        migrations.RemoveField(
            model_name="payperiod",
            name="net_pay",
        ),
        migrations.RemoveField(
            model_name="payperiod",
            name="total_hours_worked",
        ),
        migrations.AddField(
            model_name="payperiod",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="PayrollInfo",
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="pay_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payroll.payperiod"
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.store"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollentry",
            unique_together={("employee", "store", "pay_period", "date")},
        ),
    ]
