# Generated by Django 4.2.3 on 2023-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocuSignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=100, unique=True)),
                ("template_name", models.CharField(max_length=255)),
            ],
        ),
    ]
