# Generated by Django 4.2.10 on 2024-03-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0002_processeddocsigndocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processeddocsigndocument",
            name="envelope_id",
            field=models.CharField(max_length=255),
        ),
    ]
