# Generated by Django 4.2.10 on 2025-03-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0036_customuser_sin_expiration_date_and_more"),
        ("dsign", "0004_processeddocsigndocument_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="employer",
            field=models.ForeignKey(
                default=1,
                help_text="Employer associated with this template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docusign_templates",
                to="user.employer",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="docusigntemplate",
            unique_together={("employer", "template_id")},
        ),
    ]
