# Generated by Django 4.2.10 on 2025-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0038_employer_senior_contact_name"),
        ("dsign", "0005_docusigntemplate_employer_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="docusigntemplate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="docusigntemplate",
            name="employers",
            field=models.ManyToManyField(
                help_text="Employers associated with this template",
                related_name="docusign_templates",
                to="user.employer",
            ),
        ),
        migrations.RemoveField(
            model_name="docusigntemplate",
            name="employer",
        ),
    ]
