# Generated by Django 4.2.10 on 2025-03-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0038_employer_senior_contact_name"),
        ("dsign", "0006_alter_docusigntemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="employer",
            field=models.ForeignKey(
                default=1,
                help_text="Employer associated with this template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docusign_templates",
                to="user.employer",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="docusigntemplate",
            unique_together={("employer", "template_id")},
        ),
        migrations.RemoveField(
            model_name="docusigntemplate",
            name="employers",
        ),
    ]
