# Generated by Django 4.2.10 on 2025-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0007_docusigntemplate_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docusigntemplate",
            name="template_id",
            field=models.CharField(max_length=100),
        ),
    ]
