# Generated by Django 4.2.10 on 2025-03-17 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0008_alter_docusigntemplate_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
