# Generated by Django 4.2.10 on 2025-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0009_docusigntemplate_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docusigntemplate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
