# Generated by Django 4.2.10 on 2025-03-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0052_alter_newhireinvite_role"),
        ("dsign", "0010_alter_docusigntemplate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeddocsigndocument",
            name="employer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processed_documents",
                to="user.employer",
            ),
            preserve_default=False,
        ),
    ]
