# Generated by Django 4.2.10 on 2025-03-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0012_signeddocumentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocumentfile",
            name="template_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
