# Generated by Django 4.2.10 on 2025-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0013_signeddocumentfile_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="is_new_hire_template",
            field=models.BooleanField(default=False),
        ),
    ]
