# Generated by Django 4.2.10 on 2025-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0014_docusigntemplate_is_new_hire_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="is_ready_to_send",
            field=models.BooleanField(default=False),
        ),
    ]
