# Generated by Django 4.2.20 on 2025-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0015_docusigntemplate_is_ready_to_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="is_in_app_signing_template",
            field=models.BooleanField(default=False),
        ),
    ]
