# Generated by Django 4.2.20 on 2025-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0016_docusigntemplate_is_in_app_signing_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusigntemplate",
            name="is_company_document",
            field=models.BooleanField(default=False),
        ),
    ]
