# Generated by Django 4.2.20 on 2025-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0017_docusigntemplate_is_company_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeddocsigndocument",
            name="is_company_document",
            field=models.BooleanField(default=False),
        ),
    ]
