# Generated by Django 4.2.20 on 2025-04-27 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dsign", "0019_signeddocumentfile_is_company_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processeddocsigndocument",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
