# Generated by Django 4.2.20 on 2025-08-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0020_alter_processeddocsigndocument_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocumentfile",
            name="document_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="signeddocumentfile",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
