# Generated by Django 4.2.20 on 2025-08-31 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0055_newhireinvite_invited_by"),
        ("dsign", "0021_signeddocumentfile_document_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signeddocumentfile",
            name="template_name",
        ),
        migrations.AddField(
            model_name="signeddocumentfile",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="user.store",
            ),
        ),
        migrations.AlterField(
            model_name="signeddocumentfile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
