# Generated by Django 4.2.20 on 2025-09-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsign", "0022_remove_signeddocumentfile_template_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocumentfile",
            name="template_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
