# Generated by Django 4.2.3 on 2023-08-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="brief_description",
            field=models.TextField(default="Test", max_length=30),
        ),
    ]
