# Generated by Django 4.2.3 on 2023-08-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0002_incident_brief_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="brief_description",
            field=models.CharField(default="Test", max_length=30),
        ),
    ]
