# Generated by Django 4.2.3 on 2023-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0006_remove_incident_air_remove_incident_chemcomment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="product_spilled",
        ),
        migrations.AlterField(
            model_name="incident",
            name="regulatory_authorities_notified",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "yes")],
                max_length=25,
                null=True,
            ),
        ),
    ]
