# Generated by Django 4.2.3 on 2023-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0007_remove_incident_product_spilled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="eventdetails",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="gender",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="height",
            field=models.CharField(default=False, max_length=255),
        ),
    ]
