# Generated by Django 4.2.3 on 2023-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0008_alter_incident_eventdetails_alter_incident_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="brief_description",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="incident",
            name="gender",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="height",
            field=models.CharField(max_length=255),
        ),
    ]
