# Generated by Django 4.2.3 on 2023-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0009_alter_incident_brief_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section1_checkbox", models.BooleanField(default=False)),
                ("section2_checkbox", models.BooleanField(default=False)),
                ("section3_checkbox", models.BooleanField(default=False)),
                ("section4_checkbox", models.BooleanField(default=False)),
                ("section5_checkbox", models.BooleanField(default=False)),
            ],
        ),
    ]
