# Generated by Django 4.2.3 on 2023-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0010_incident2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="actionstaken",
            field=models.TextField(null=True),
        ),
    ]
