# Generated by Django 4.2.3 on 2023-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0013_alter_incident_actionstaken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="eventdetails",
            field=models.CharField(null=True),
        ),
    ]
