# Generated by Django 4.2.3 on 2023-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0014_alter_incident_eventdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Incident2",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="brief_description",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="image_folder",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="incident_images",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="product_that_was_spilled",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="regulatory_authorities_notified",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="source_impacted",
        ),
        migrations.AddField(
            model_name="incident",
            name="air",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="chemcomment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="chemical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="deiselexhaustfluid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="diesel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="gas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="land",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="rna",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="rno",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="ryes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="sewage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="sno",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="sother",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="syes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="water",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="wildlife",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="incident",
            name="actionstaken",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="beardmoustache",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="bumpersticker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="color",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="complexion",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="correctiveactions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="damage",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="direction",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventdate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventdetails",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventtime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eyeeyeglasses",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="gender",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="haircolor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="haircut",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="hat",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="height",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="licencenumber",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="makemodel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="othertext",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="pcase",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="rcomment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="reportedby",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="reportedbynumber",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="s2comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="scars",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="scomment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="shirt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="shoes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolcards",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolenothervalue",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolfuel",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stollottery",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolother",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltobacco",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltransactions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="tatoos",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="trousers",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="voice",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="volumerelease",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="weight",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
