# Generated by Django 4.2.3 on 2023-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0015_delete_incident2_remove_incident_brief_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="brief_description",
            field=models.CharField(default="", max_length=30),
        ),
    ]
