# Generated by Django 4.2.3 on 2023-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0016_incident_brief_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="othertext",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="pcase",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="rcomment",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="s2comment",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="scomment",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolcards",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolfuel",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stollottery",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolother",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltobacco",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltransactions",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="volumerelease",
            field=models.CharField(blank=True),
        ),
    ]
