# Generated by Django 4.2.3 on 2023-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0018_alter_incident_actionstaken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="chemcomment",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventdate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventdetails",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventtime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolenothervalue",
            field=models.CharField(blank=True),
        ),
    ]
