# Generated by Django 4.2.3 on 2023-08-20 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0019_alter_incident_chemcomment_alter_incident_eventdate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="employer",
        ),
    ]
