# Generated by Django 4.2.3 on 2023-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0020_remove_incident_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="eventdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="eventtime",
            field=models.TimeField(null=True),
        ),
    ]
