# Generated by Django 4.2.3 on 2023-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0021_alter_incident_eventdate_alter_incident_eventtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="image_folder",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_images",
            field=models.ManyToManyField(
                related_name="incident_images", to="incident.incident_files"
            ),
        ),
    ]
