# Generated by Django 4.2.3 on 2023-08-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_store_employer"),
        ("incident", "0023_remove_incident_incident_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employer",
            ),
        ),
    ]
