# Generated by Django 4.2.3 on 2023-08-21 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0024_incident_employer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="employer",
            new_name="user_employer",
        ),
    ]
