# Generated by Django 4.2.10 on 2024-08-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0027_remove_externalrecipient_role_and_more"),
        ("incident", "0025_rename_employer_incident_user_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("robbery", models.BooleanField(default=False)),
                ("breakandenter", models.BooleanField(default=False)),
                ("assault", models.BooleanField(default=False)),
                ("bombthreat", models.BooleanField(default=False)),
                ("majorfireorexplosion", models.BooleanField(default=False)),
                ("fatality", models.BooleanField(default=False)),
                ("criticalinjury", models.BooleanField(default=False)),
                ("policeagency", models.CharField(default="", max_length=60)),
                ("officerdetails", models.TextField()),
                ("eventdate", models.DateField(null=True)),
                ("eventtime", models.TimeField(null=True)),
                ("reportedby", models.CharField(blank=True, max_length=255)),
                ("policefilenumber", models.CharField(blank=True, max_length=255)),
                ("policecalledyes", models.BooleanField(default=False)),
                ("policecalledno", models.BooleanField(default=False)),
                ("policeattendyes", models.BooleanField(default=False)),
                ("policeattendno", models.BooleanField(default=False)),
                ("gsoccalledyes", models.BooleanField(default=False)),
                ("gsoccalledno", models.BooleanField(default=False)),
                ("damagedetails", models.TextField()),
                ("stolencash", models.BooleanField(default=False)),
                ("stolcash", models.CharField(blank=True)),
                ("stolencards", models.BooleanField(default=False)),
                ("stolcards", models.CharField(blank=True)),
                ("stolentobacco", models.BooleanField(default=False)),
                ("stoltobacco", models.CharField(blank=True)),
                ("stolenlottery", models.BooleanField(default=False)),
                ("stollottery", models.CharField(blank=True)),
                ("stolenother", models.BooleanField(default=False)),
                ("stolother", models.CharField(blank=True)),
                ("stolenothervalue", models.CharField(blank=True)),
                ("stolenna", models.BooleanField(default=False)),
                ("gender", models.CharField(blank=True, max_length=255)),
                ("age", models.CharField(blank=True, max_length=255)),
                ("height", models.CharField(blank=True, max_length=255)),
                ("weight", models.CharField(blank=True, max_length=255)),
                ("haircolor", models.CharField(blank=True, max_length=255)),
                ("haircut", models.CharField(blank=True, max_length=255)),
                ("complexion", models.CharField(blank=True, max_length=255)),
                ("beardmoustache", models.CharField(blank=True, max_length=255)),
                ("eyeeyeglasses", models.CharField(blank=True, max_length=255)),
                ("licencenumber", models.CharField(blank=True, max_length=255)),
                ("makemodel", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(blank=True, max_length=255)),
                ("scars", models.CharField(blank=True, max_length=255)),
                ("tatoos", models.CharField(blank=True, max_length=255)),
                ("hat", models.CharField(blank=True, max_length=255)),
                ("shirt", models.CharField(blank=True, max_length=255)),
                ("trousers", models.CharField(blank=True, max_length=255)),
                ("shoes", models.CharField(blank=True, max_length=255)),
                ("voice", models.CharField(blank=True, max_length=255)),
                ("bumpersticker", models.CharField(blank=True, max_length=255)),
                ("direction", models.CharField(blank=True, max_length=255)),
                ("damage", models.CharField(blank=True, max_length=255)),
                ("image_folder", models.CharField(max_length=255, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majorincidents",
                        to="user.store",
                    ),
                ),
                (
                    "user_employer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.employer",
                    ),
                ),
            ],
        ),
    ]
