# Generated by Django 4.2.10 on 2024-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0026_majorincident"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorincident",
            name="brief_description",
            field=models.CharField(default="", max_length=60),
        ),
    ]
