# Generated by Django 4.2.10 on 2024-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0027_majorincident_brief_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorincident",
            name="approximateyearmakemodel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="majorincident",
            name="colour",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="majorincident",
            name="destinguishablefeatures",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="majorincident",
            name="licenceplatenumber",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
