# Generated by Django 4.2.10 on 2024-08-27 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0028_majorincident_approximateyearmakemodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="majorincident",
            old_name="destinguishablefeatures",
            new_name="distinguishablefeatures",
        ),
    ]
