# Generated by Django 4.2.10 on 2024-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0029_rename_destinguishablefeatures_majorincident_distinguishablefeatures",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="majorincident",
            name="damagetoproperty",
            field=models.CharField(default=False),
        ),
    ]
