# Generated by Django 4.2.10 on 2024-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0030_majorincident_damagetoproperty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorincident",
            name="damagetoproperty",
            field=models.TextField(),
        ),
    ]
