# Generated by Django 4.2.10 on 2024-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0031_alter_majorincident_damagetoproperty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorincident",
            name="damagetoproperty",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="majorincident",
            name="officerdetails",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="majorincident",
            name="policeagency",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
