# Generated by Django 4.2.10 on 2024-08-27 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0032_alter_majorincident_damagetoproperty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="majorincident",
            name="damagedetails",
        ),
    ]
