# Generated by Django 4.2.10 on 2024-12-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0033_remove_majorincident_damagedetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="queued_for_sending",
            field=models.BooleanField(
                default=False, help_text="Indicates if this file is queued for sending."
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="send_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of send attempts."
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, help_text="The timestamp when the file was sent.", null=True
            ),
        ),
    ]
