# Generated by Django 4.2.10 on 2024-12-26 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0034_incident_queued_for_sending_incident_send_attempts_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="send_attempts",
        ),
    ]
