# Generated by Django 4.2.10 on 2024-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0035_remove_incident_send_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
