# Generated by Django 4.2.10 on 2024-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0036_incident_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="do_not_send",
            field=models.BooleanField(default=False),
        ),
    ]
