# Generated by Django 4.2.10 on 2025-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0039_rename_other_incident_staff_incident_eventtimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="emergency_contractor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="emergency_no",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="emergency_not_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="emergency_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="emergency_responders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="emergency_site_staff",
            field=models.BooleanField(default=False),
        ),
    ]
