# Generated by Django 4.2.10 on 2025-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0040_incident_emergency_contractor_incident_emergency_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="causalfactors",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
