# Generated by Django 4.2.10 on 2025-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0041_alter_incident_causalfactors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="determincauses",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="preventiveactions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
