# Generated by Django 4.2.29 on 2026-08-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0042_alter_incident_determincauses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="contractor_company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="contractor_involved",
            field=models.BooleanField(
                blank=True,
                help_text="Was a contractor involved in the incident?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="regulatory_notification_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference or case number supplied by the regulatory authority.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="spill_contained",
            field=models.BooleanField(
                blank=True, help_text="Was the spill contained?", null=True
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="spill_contained_concrete_asphalt",
            field=models.BooleanField(
                default=False,
                help_text="Was the spill contained to concrete or asphalt?",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="spill_contained_oil_water_separator",
            field=models.BooleanField(
                default=False,
                help_text="Was the spill contained to the oil-water separator?",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="spill_migrated_offsite",
            field=models.BooleanField(
                blank=True, help_text="Did the spill migrate offsite?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="causalfactors",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="chemcomment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="determincauses",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="emergency_responders",
            field=models.BooleanField(
                default=False,
                help_text="Examples include 911, fire, police, or other responders.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="image_folder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="othertext",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="pcase",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="preventiveactions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="rcomment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="s2comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="scomment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolcards",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolenothervalue",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolfuel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stollottery",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stolother",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltobacco",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="stoltransactions",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="incident",
            name="volumerelease",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
