# Generated by Django 4.2.29 on 2026-08-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0043_incident_contractor_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="clothing_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="damage_value",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="gsoc_called",
            field=models.BooleanField(
                blank=True,
                help_text="Was the Global Security Operations Center called?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="police_agency",
            field=models.CharField(
                blank=True,
                help_text="Police agency, such as RCMP, OPP, or local police.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="police_attended",
            field=models.BooleanField(
                blank=True, help_text="Did police attend the site?", null=True
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="police_officer_badge_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="incident",
            name="police_officer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="police_officer_rank",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_assault",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_bomb_threat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_break_and_enter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_critical_injury",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_fatality",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_major_fire_explosion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="security_robbery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="suspect_age",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="incident",
            name="theft_cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="theft_cash_value",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="vehicle_distinguishing_features",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="vehicle_year",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
