# Generated by Django 4.2.20 on 2025-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reclose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_number", models.PositiveIntegerField()),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cat_post_host", models.PositiveIntegerField(default=0)),
                ("drive_offs", models.PositiveIntegerField(default=0)),
                (
                    "purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ppts_redemptions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="PPTS Redemptions ($1)",
                    ),
                ),
                (
                    "lotto_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "uber_eats",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "skip",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="SkipTheDishes",
                    ),
                ),
                (
                    "drive_off_recovery",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cash_safe_drops",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "last_safe_drop",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "in_brink",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="In Brink",
                    ),
                ),
            ],
        ),
    ]
