# Generated by Django 4.2.20 on 2025-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reclose", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclose",
            name="store_number",
            field=models.CharField(default=1616, max_length=20),
            preserve_default=False,
        ),
    ]
