# Generated by Django 4.2.20 on 2025-08-04 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reclose", "0002_reclose_store_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reclose",
            new_name="RecClose",
        ),
    ]
