# Generated by Django 4.2.20 on 2025-08-04 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reclose", "0003_rename_reclose_recclose"),
    ]

    operations = [
        migrations.AddField(
            model_name="recclose",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
