# Generated by Django 4.2.20 on 2025-08-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("reclose", "0004_recclose_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="recclose",
            name="user_employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employer",
            ),
        ),
    ]
