# Generated by Django 4.2.29 on 2026-03-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0057_store_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('position_interest', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('either', 'Either')], default='either', max_length=20)),
                ('availability', models.TextField(blank=True)),
                ('has_transportation', models.BooleanField(default=False)),
                ('eligible_to_work_in_canada', models.BooleanField(default=False)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('direct', 'Direct'), ('other', 'Other')], default='direct', max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recruit/resumes/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('screening', 'Screening'), ('interview', 'Interview'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruit_applicants', to='user.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
