# Generated by Django 4.2.29 on 2026-03-28 20:19

import arl.recruit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitapplicant',
            name='resume_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruitapplicant',
            name='resume_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitapplicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=arl.recruit.models.recruit_resume_upload_path),
        ),
    ]
