# Generated by Django 4.2.29 on 2026-03-28 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_recruitapplicant_resume_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitapplicant',
            name='resume',
        ),
        migrations.AddField(
            model_name='recruitapplicant',
            name='resume_object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recruitapplicant',
            name='resume_folder',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255),
        ),
    ]
