name: Django Tests part two

on:
    push:
        branches:
        -https://github.com/Paulfuther/Django-arl/tree/dev-v1.0.01

    pull_request:
        branches:
        -https://github.com/Paulfuther/Django-arl/tree/dev-v1.0.01

jobs:
    build:

    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set p Python 3.9
          uses: actions/setup-python@v2
          with: 
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirments.txt

        - name: Lint with flake8
          run: |
            pip install flask8
            flake8

        - name: Coverage report
          run: |
            pip install coverage
            coverage run manage.py test
            coverage report
            
        - name: Django Testing
          run: |
            python3 manage.py test
