name: Django Tests

on:
  push:
    branches:
      - dev-v1.0.01
  pull_request:
    branches:
      - dev-v1.0.01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set Twilio credentials
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8

    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report

    - name: Django Testing
      run: |
        python manage.py test



