# Generated by Django 4.2.10 on 2025-02-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0031_smsoptout"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAPIKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twilio_account_sid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "twilio_service_sid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sendgrid_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropbox_access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="user.employer",
                    ),
                ),
            ],
        ),
    ]
