# Generated by Django 4.2.10 on 2025-02-15 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0002_rename_twilio_account_sid_tenantapikeys_account_sid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantapikeys",
            name="auth_token",
        ),
    ]
