# Generated by Django 4.2.10 on 2025-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0003_remove_tenantapikeys_auth_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantapikeys",
            name="api_key",
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="auth_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="sender_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Error", "Error")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenantapikeys",
            name="service_name",
            field=models.CharField(max_length=50),
        ),
    ]
