# Generated by Django 4.2.10 on 2025-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0004_remove_tenantapikeys_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantapikeys",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="messaging_service_sid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="verified_sender_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="tenantapikeys",
            name="service_name",
            field=models.CharField(
                choices=[("twilio", "Twilio"), ("sendgrid", "SendGrid")], max_length=50
            ),
        ),
    ]
