# Generated by Django 4.2.10 on 2025-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0005_tenantapikeys_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantapikeys",
            name="service_name",
        ),
        migrations.AddField(
            model_name="tenantapikeys",
            name="notify_service_sid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
