# Generated by Django 4.2.10 on 2025-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0006_remove_tenantapikeys_service_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantapikeys",
            name="phone_number_sid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
