# Generated by Django 4.2.10 on 2025-03-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0007_tenantapikeys_phone_number_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantapikeys",
            name="service_name",
            field=models.CharField(
                choices=[("twilio", "Twilio"), ("sendgrid", "SendGrid")],
                default="twilio",
                max_length=20,
            ),
        ),
    ]
