# Generated by Django 4.2.10 on 2025-03-15 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0008_tenantapikeys_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantapikeys",
            name="service_name",
        ),
    ]
