# Generated by Django 4.2.10 on 2025-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0010_stripeplan_stripepayment_employerrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerrequest",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employerrequest",
            name="senior_contact_name",
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="company_name",
            field=models.CharField(default="ACME", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="senior_contact_first_name",
            field=models.CharField(default="john", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employerrequest",
            name="senior_contact_last_name",
            field=models.CharField(default="john", max_length=100),
            preserve_default=False,
        ),
    ]
