# Generated by Django 4.2.10 on 2024-10-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0027_remove_externalrecipient_role_and_more"),
        ("quiz", "0002_saltlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saltlog",
            old_name="location",
            new_name="area_salted",
        ),
        migrations.RemoveField(
            model_name="saltlog",
            name="user",
        ),
        migrations.AlterField(
            model_name="saltlog",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.store"
            ),
        ),
    ]
