# Generated by Django 4.2.20 on 2025-08-24 18:24

import arl.quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_checklist_checklisttemplate_checklisttemplateitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitem",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=arl.quiz.models.checklist_photo_upload_to,
            ),
        ),
    ]
