# Generated by Django 4.2.10 on 2024-10-22 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_rename_location_saltlog_area_salted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saltlog",
            name="time_salted",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
