# Generated by Django 4.2.20 on 2025-08-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0054_remove_stripepayment_employer_delete_employerrequest_and_more"),
        ("quiz", "0003_alter_checklistitem_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklists",
                to="user.store",
            ),
        ),
    ]
