# Generated by Django 4.2.10 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_saltlog_time_salted"),
    ]

    operations = [
        migrations.AddField(
            model_name="saltlog",
            name="image_folder",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
