# Generated by Django 4.2.10 on 2024-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_saltlog_image_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saltlog",
            name="date_salted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="saltlog",
            name="time_salted",
            field=models.TimeField(null=True),
        ),
    ]
