# Generated by Django 4.2.10 on 2024-10-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0027_remove_externalrecipient_role_and_more"),
        ("quiz", "0006_alter_saltlog_date_salted_alter_saltlog_time_salted"),
    ]

    operations = [
        migrations.AddField(
            model_name="saltlog",
            name="user_employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employer",
            ),
        ),
    ]
